import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { switchThemeDuration } from "./constants/switch-theme-durations";
import { ThemeProvider } from "./context/ThemeProvider";


const ubuntu = Ubuntu({ subsets: ["latin"], weight: '300' });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
      <html lang="en" suppressHydrationWarning >
      <body className={`ubuntu.className ${switchThemeDuration}`}>
        <ThemeProvider attribute='class'>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
